"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import { Box, Container, CssBaseline } from "@mui/material";
import Sidebar from "@/components/ui/Sidebar";
import DashboardHeader from "@/components/ui/DashboardHeader";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Next-MUI Starter",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box sx={{ display: "flex" }}>
            <CssBaseline />
            <Sidebar />
            <Box sx={{ flexGrow: 1 }}>
              <DashboardHeader />
              <Container maxWidth="lg">{children}</Container>
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
